apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitsources.devopsconsole.openshift.io
spec:
  group: devopsconsole.openshift.io
  names:
    kind: GitSource
    listKind: GitSourceList
    plural: gitsources
    singular: gitsource
    shortNames:
      - gitsrc
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            url:
              type: string
            ref:
              type: string
            contextDir:
              type: string
            httpProxy:
              type: string
            httpsProxy:
              type: string
            noProxy:
              type: string
            sourceSecret:
              type: string
  version: v1alpha1