apiVersion: apps/v1
kind: Deployment
metadata:
  name: devconsole-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: devconsole-operator
  template:
    metadata:
      labels:
        name: devconsole-operator
    spec:
      serviceAccountName: devconsole-operator
      containers:
        - name: devconsole-operator
          # Replace this with the built image name
          image: 172.30.1.1:5000/devconsole/devconsole-operator:latest
          command:
          - devconsole-operator
          imagePullPolicy: Always # replace with IfNotPresent for local dev to avoid pulling image and use docker cached image
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "devconsole-operator"
            - name: APP_SERVICE_IMAGE_NAME
              value: "jarifibrahim/boilerplate-app" # change this to actual image when we have it
