kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devopsconsole-operator
subjects:
- kind: ServiceAccount
  name: devopsconsole-operator
  namespace: devopsconsole
roleRef:
  kind: Role
  name: devopsconsole-operator
  apiGroup: rbac.authorization.k8s.io
