apiVersion: devconsole.openshift.io/v1alpha1
kind: EnvDeployment
metadata:
  name: my-local-deployment
spec:
  # Add fields here
  environmentRef:
    kind: Environment # this must be Environment
    name: devenv # this must match the name of the Environment you wish to point to
    apiGroup: devconsole.openshift.io
  deploymentRef:
    kind: DeploymentConfig # this must be DeploymentConfig
    name: my-deployment # this must match the name of the DeploymentConfig you wish to point to
    apiGroup: apps.openshift.io
